spring.application.name=order-service

#Datasource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/orders
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update


product-service.base-url=http://localhost:8081
payment-service.base-url=http://localhost:8082