spring.application.name=delivery-service

#Datasource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/delivery
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

server.port=8083

#Spring Kafka
spring.kafka.consumer.group-id=delivery-service-group
spring.kafka.bootstrap-servers=localhost:9092

order-paid-topic=orders.events
delivery-assigned-topic=delivery.events
